project:
  type: book

book:
  title: "book"
  author: "Daniel E Gonzalez"
  date: "24/4/2023"
  
  
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
    
render:
  output_dir: docs # Aquí se especifica el directorio de salida    

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

