project:
  type: book

book:
  title: "book"
  author: "Daniel E Gonzalez"
  date: "24/4/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
bibliography: references.bib

render:
  output_dir: docs

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

publish:
  - provider: pages
    local_dir: docs
    target_branch: gh-pages
